# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  displayName: Building The Module
  inputs:
    filePath: '.\Powershell\build.ps1'
    pwsh: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '.\output\UniversalDashboard.MaterialUICarousel' 
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/UniversalDashboard.MaterialUICarousel.zip' 

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'UniversalDashboard.MaterialUICarousel'
    targetPath: $(Build.ArtifactStagingDirectory)

- task: GitHubRelease@1
  displayName: 'GitHub release (create)'
  inputs:
    gitHubConnection: 'github alongvili'
    tagSource: userSpecifiedTag
    tag: v1.0
    title: UniversalDashboard.MaterialUICarousel

